name: Tch-57 Access token conditional

on:
  push:
    branches-ignore:
      - 'wip-**'
      - '**-wip'
      - 'master'
      - 'alpha'
      - 'beta'
      - 'next'

jobs:
  build:
    name: Test conditional use of personal access token

    env:
      CI: true
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.NONEXISTENT_TOKEN || secrets.GITHUB_TOKEN }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check token 1
        if: github.secrets.PERSONAL_ACCESS_TOKEN
        run: echo "Token is available"
      - name: Check token 2
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          NONEXISTENT_TOKEN: ${{ secrets.NONEXISTENT_TOKEN }}
        run: |
          if test -n "$PERSONAL_ACCESS_TOKEN" ; then echo "PAT is available" ; else echo "PAT is NOT available" ; fi
          if test -n "$NONEXISTENT_TOKEN" ; then echo "Nonexistent token is available" ; else echo "Nonexistent token is NOT available" ; fi
